---
# Per environment values which override defaults in hmpps-court-data-ingestion-api/values.yaml

generic-service:
  ingress:
    host: court-data-ingestion-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    CORE_PERSON_API_URL: "https://hmpps-person-record.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_URL: "https://document-api.hmpps.service.justice.gov.uk"
    HMPPS_COURT-CASES-RELEASE-DATES_API_URL: "https://court-cases-release-dates-api.hmpps.service.justice.gov.uk"
    HMPPS_COURT-REGISTER_API_URL: "https://court-register-api.hmpps.service.justice.gov.uk"
    HMCTS_SUBSCRIPTION_CALLBACK_URL: "https://czbsgqfdwd.execute-api.eu-west-2.amazonaws.com/production/ingest"
    HMCTS_SUBSCRIPTION_API_URL: "https://amp.cjscp.org.uk/hrds"
    HMCTS_COURTHOUSE_API_URL: "https://amp.cjscp.org.uk/rcc"
    HMCTS_COURT_SCHEDULE_API_URL: "https://amp.cjscp.org.uk/slc"
    HMCTS_COURT_DEFENDANT_API_URL: "https://amp.cjscp.org.uk/dl"
    HMCTS_PCR_API_URL: "https://amp.cjscp.org.uk/pcr"
    DEFENDANT_RESOLUTION_ENABLED: "true"
    HMCTS_AUTH_URL: "https://login.microsoftonline.com/77f54315-6dde-4fe7-9e17-74762c3eb096"
    HMCTS_UPDATE_SUBSCRIPTION_ON_STARTUP: true
    HMCTS_EVENT_TYPES: "PRISON_COURT_REGISTER_GENERATED, WEE_CustodialSentence, OXE_DetentionAndTraining, WEE_Remand, WEE_RemandAfterBailAppealByProsecutor, WEE_CommittalToCrownCourtForSentence, WEE_CommittalToCrownCourtForConsiderationOfTheQuestionOfBailOnAChargeOfMurder, WEE_CommittalToCrownCourtAuthorityToHoldInYouthDetentionAccommodation, WEE_SendingToCrownCourtForTrial"
    HMCTS_SUBSCRIPTION_ENABLED: true
    ENVIRONMENT_NAME: prod
    HMCTS_RATE_LIMIT: 0.4
    OFFENCE_DATA_ENABLED: false

  postgresDatabaseRestore:
    enabled: true
    timeout: 3600
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_queue"
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_dlq"
    - "calculate-release-dates-team-prod-hmpps_court_data_prisoner_created_queue"
    - "calculate-release-dates-team-prod-hmpps_court_data_prisoner_created_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1

generic-data-analytics-extractor:
  enabled: true
