---
# Per environment values which override defaults in hmpps-court-data-ingestion-api/values.yaml

generic-service:
  ingress:
    host: court-data-ingestion-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    CORE_PERSON_API_URL: "https://hmpps-person-record.hmpps.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_URL: "https://document-api.hmpps.service.justice.gov.uk"
    HMCTS_SUBSCRIPTION_CALLBACK_URL: "https://czbsgqfdwd.execute-api.eu-west-2.amazonaws.com/production/ingest"
    HMCTS_SUBSCRIPTION_API_URL: "https://tmc.dev.cjscp.org.uk/hrds"
    HMCTS_AUTH_URL: "https://login.microsoftonline.com/77f54315-6dde-4fe7-9e17-74762c3eb096"
    HMCTS_EVENT_TYPES: "PRISON_COURT_REGISTER_GENERATED"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_queue"
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_dlq"
    - "calculate-release-dates-team-prod-hmpps_court_data_prisoner_created_queue"
    - "calculate-release-dates-team-prod-hmpps_court_data_prisoner_created_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
