---
# Per environment values which override defaults in hmpps-court-data-ingestion-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: court-data-ingestion-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    CORE_PERSON_API_URL: "https://hmpps-person-record-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    HMPPS_DOCUMENT_MANAGEMENT_API_URL: "https://document-api-preprod.hmpps.service.justice.gov.uk"
    HMPPS_COURT-CASES-RELEASE-DATES_API_URL: "https://court-cases-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    HMCTS_SUBSCRIPTION_CALLBACK_URL: "https://hxpwmnx4ef.execute-api.eu-west-2.amazonaws.com/preproduction/ingest"
    HMCTS_SUBSCRIPTION_API_URL: "https://amp.cjscp.org.uk/hrds"
    HMCTS_COURTHOUSE_API_URL: "https://amp.cjscp.org.uk/rcc"
    HMCTS_COURT_SCHEDULE_API_URL: "https://amp.cjscp.org.uk/slc"
    HMCTS_COURT_DEFENDANT_API_URL: "https://amp.cjscp.org.uk/dl"
    DEFENDANT_RESOLUTION_ENABLED: "false"
    HMCTS_AUTH_URL: "https://login.microsoftonline.com/77f54315-6dde-4fe7-9e17-74762c3eb096"
    HMCTS_UPDATE_SUBSCRIPTION_ON_STARTUP: true
    HMCTS_EVENT_TYPES: "ALL_EVENT_TYPES"
    HMCTS_SUBSCRIPTION_ENABLED: true
    EXTRACTION_CORPUSSAMPLER_ENABLED: "true"
    ENVIRONMENT_NAME: preprod

  scheduledDowntime:
    enabled: true
    # Start at 6:55am Monday-Friday - 10 minutes after hmpps-person-record
    startupOverride: '55 6 * * 1-5'
    timeZone: Europe/London

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "calculate-release-dates-team-preprod-hmpps_court_data_ingestion_queue"
    - "calculate-release-dates-team-preprod-hmpps_court_data_ingestion_dlq"
    - "calculate-release-dates-team-preprod-hmpps_court_data_prisoner_created_queue"
    - "calculate-release-dates-team-preprod-hmpps_court_data_prisoner_created_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
